# Generated by Django 4.0.3 on 2022-04-07 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_jobs_referencias_delete_test_jobs_referencias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.DeleteModel(
            name='Referencias',
        ),
    ]
